// <copyright file="GlobalSuppressions.cs" company="Microsoft">
// Copyright (c) Microsoft. All rights reserved.
// </copyright>

// This file is used by Code Analysis to maintain SuppressMessage attributes that are applied to this project.
// Project-level suppressions either have no target or are given a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for telemetry message.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnConversationUpdateActivityAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IConversationUpdateActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Not required to catch specific exception.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnConversationUpdateActivityAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IConversationUpdateActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for telemetry message.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnAdaptiveCardSubmitInPersonalChatAsync(Microsoft.Bot.Schema.IMessageActivity,Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IMessageActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for telemetry message.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnMessageActivityInChannelAsync(Microsoft.Bot.Schema.IMessageActivity,Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IMessageActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Not required to catch specific exception.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnTurnAsync(Microsoft.Bot.Builder.ITurnContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Not required to catch specific exception.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnTeamsTaskModuleSubmitAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IInvokeActivity},Microsoft.Bot.Schema.Teams.TaskModuleRequest,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.Bot.Schema.Teams.TaskModuleResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Not required to catch specific exception.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnTeamsMessagingExtensionSubmitActionAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IInvokeActivity},Microsoft.Bot.Schema.Teams.MessagingExtensionAction,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.Bot.Schema.Teams.MessagingExtensionActionResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Not required to catch specific exception.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnTeamsMessagingExtensionFetchTaskAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IInvokeActivity},Microsoft.Bot.Schema.Teams.MessagingExtensionAction,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.Bot.Schema.Teams.MessagingExtensionActionResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for telemetry message.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnMessageActivityInPersonalChatAsync(Microsoft.Bot.Schema.IMessageActivity,Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IMessageActivity},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Not required to validate it for null as it will never be null.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Bots.FaqPlusPlusBot.OnTeamsMessagingExtensionSubmitActionAsync(Microsoft.Bot.Builder.ITurnContext{Microsoft.Bot.Schema.IInvokeActivity},Microsoft.Bot.Schema.Teams.MessagingExtensionAction,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.Bot.Schema.Teams.MessagingExtensionActionResponse}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.MessagingExtensionQnaCard.GetEndUserAdaptiveCard(System.String,Microsoft.Azure.CognitiveServices.Knowledge.QnAMaker.Models.QnASearchResult)~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.MessagingExtensionQnaCard.DeleteEntry(System.String,System.String)~AdaptiveCards.AdaptiveCard")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.ResponseCard.GetCard(System.String,System.String,System.String)~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.WelcomeCard.GetCard(System.String)~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.UnrecognizedInputCard.GetCard(System.String)~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.AskAnExpertCard.GetCard(System.Boolean,Microsoft.Teams.Apps.FAQPlusPlus.Common.Models.AskAnExpertCardPayload)~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.ShareFeedbackCard.GetCard(System.Boolean,Microsoft.Teams.Apps.FAQPlusPlus.Common.Models.ShareFeedbackCardPayload)~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.WelcomeTeamCard.GetCard~Microsoft.Bot.Schema.Attachment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Not required to create resources for command related constants.", Scope = "member", Target = "~M:Microsoft.Teams.Apps.FAQPlusPlus.Cards.UnrecognizedTeamInputCard.GetCard~Microsoft.Bot.Schema.Attachment")]